// This file is generated by rust-protobuf 2.6.2. Do not edit
// @generated

// https://github.com/Manishearth/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy)]

#![cfg_attr(rustfmt, rustfmt_skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unsafe_code)]
#![allow(unused_imports)]
#![allow(unused_results)]

use protobuf::Message as Message_imported_for_functions;
use protobuf::ProtobufEnum as ProtobufEnum_imported_for_functions;

#[derive(PartialEq,Clone,Default)]
pub struct Regression {
    // message fields
    pub value: f32,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a Regression {
    fn default() -> &'a Regression {
        <Regression as ::protobuf::Message>::default_instance()
    }
}

impl Regression {
    pub fn new() -> Regression {
        ::std::default::Default::default()
    }

    // float value = 1;


    pub fn get_value(&self) -> f32 {
        self.value
    }
    pub fn clear_value(&mut self) {
        self.value = 0.;
    }

    // Param is passed by value, moved
    pub fn set_value(&mut self, v: f32) {
        self.value = v;
    }
}

impl ::protobuf::Message for Regression {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    if wire_type != ::protobuf::wire_format::WireTypeFixed32 {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_float()?;
                    self.value = tmp;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if self.value != 0. {
            my_size += 5;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream) -> ::protobuf::ProtobufResult<()> {
        if self.value != 0. {
            os.write_float(1, self.value)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn ::std::any::Any {
        self as &dyn ::std::any::Any
    }
    fn as_any_mut(&mut self) -> &mut dyn ::std::any::Any {
        self as &mut dyn ::std::any::Any
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<dyn ::std::any::Any> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> Regression {
        Regression::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeFloat>(
                    "value",
                    |m: &Regression| { &m.value },
                    |m: &mut Regression| { &mut m.value },
                ));
                ::protobuf::reflect::MessageDescriptor::new::<Regression>(
                    "Regression",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static Regression {
        static mut instance: ::protobuf::lazy::Lazy<Regression> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const Regression,
        };
        unsafe {
            instance.get(Regression::new)
        }
    }
}

impl ::protobuf::Clear for Regression {
    fn clear(&mut self) {
        self.value = 0.;
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for Regression {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for Regression {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct RegressionResult {
    // message fields
    pub regressions: ::protobuf::RepeatedField<Regression>,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a RegressionResult {
    fn default() -> &'a RegressionResult {
        <RegressionResult as ::protobuf::Message>::default_instance()
    }
}

impl RegressionResult {
    pub fn new() -> RegressionResult {
        ::std::default::Default::default()
    }

    // repeated .tensorflow.Regression regressions = 1;


    pub fn get_regressions(&self) -> &[Regression] {
        &self.regressions
    }
    pub fn clear_regressions(&mut self) {
        self.regressions.clear();
    }

    // Param is passed by value, moved
    pub fn set_regressions(&mut self, v: ::protobuf::RepeatedField<Regression>) {
        self.regressions = v;
    }

    // Mutable pointer to the field.
    pub fn mut_regressions(&mut self) -> &mut ::protobuf::RepeatedField<Regression> {
        &mut self.regressions
    }

    // Take field
    pub fn take_regressions(&mut self) -> ::protobuf::RepeatedField<Regression> {
        ::std::mem::replace(&mut self.regressions, ::protobuf::RepeatedField::new())
    }
}

impl ::protobuf::Message for RegressionResult {
    fn is_initialized(&self) -> bool {
        for v in &self.regressions {
            if !v.is_initialized() {
                return false;
            }
        };
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_repeated_message_into(wire_type, is, &mut self.regressions)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        for value in &self.regressions {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        };
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream) -> ::protobuf::ProtobufResult<()> {
        for v in &self.regressions {
            os.write_tag(1, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        };
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn ::std::any::Any {
        self as &dyn ::std::any::Any
    }
    fn as_any_mut(&mut self) -> &mut dyn ::std::any::Any {
        self as &mut dyn ::std::any::Any
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<dyn ::std::any::Any> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> RegressionResult {
        RegressionResult::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_repeated_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<Regression>>(
                    "regressions",
                    |m: &RegressionResult| { &m.regressions },
                    |m: &mut RegressionResult| { &mut m.regressions },
                ));
                ::protobuf::reflect::MessageDescriptor::new::<RegressionResult>(
                    "RegressionResult",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static RegressionResult {
        static mut instance: ::protobuf::lazy::Lazy<RegressionResult> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const RegressionResult,
        };
        unsafe {
            instance.get(RegressionResult::new)
        }
    }
}

impl ::protobuf::Clear for RegressionResult {
    fn clear(&mut self) {
        self.regressions.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for RegressionResult {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for RegressionResult {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct RegressionRequest {
    // message fields
    pub model_spec: ::protobuf::SingularPtrField<super::model::ModelSpec>,
    pub input: ::protobuf::SingularPtrField<super::input::Input>,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a RegressionRequest {
    fn default() -> &'a RegressionRequest {
        <RegressionRequest as ::protobuf::Message>::default_instance()
    }
}

impl RegressionRequest {
    pub fn new() -> RegressionRequest {
        ::std::default::Default::default()
    }

    // .tensorflow.ModelSpec model_spec = 1;


    pub fn get_model_spec(&self) -> &super::model::ModelSpec {
        self.model_spec.as_ref().unwrap_or_else(|| super::model::ModelSpec::default_instance())
    }
    pub fn clear_model_spec(&mut self) {
        self.model_spec.clear();
    }

    pub fn has_model_spec(&self) -> bool {
        self.model_spec.is_some()
    }

    // Param is passed by value, moved
    pub fn set_model_spec(&mut self, v: super::model::ModelSpec) {
        self.model_spec = ::protobuf::SingularPtrField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_model_spec(&mut self) -> &mut super::model::ModelSpec {
        if self.model_spec.is_none() {
            self.model_spec.set_default();
        }
        self.model_spec.as_mut().unwrap()
    }

    // Take field
    pub fn take_model_spec(&mut self) -> super::model::ModelSpec {
        self.model_spec.take().unwrap_or_else(|| super::model::ModelSpec::new())
    }

    // .tensorflow.Input input = 2;


    pub fn get_input(&self) -> &super::input::Input {
        self.input.as_ref().unwrap_or_else(|| super::input::Input::default_instance())
    }
    pub fn clear_input(&mut self) {
        self.input.clear();
    }

    pub fn has_input(&self) -> bool {
        self.input.is_some()
    }

    // Param is passed by value, moved
    pub fn set_input(&mut self, v: super::input::Input) {
        self.input = ::protobuf::SingularPtrField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_input(&mut self) -> &mut super::input::Input {
        if self.input.is_none() {
            self.input.set_default();
        }
        self.input.as_mut().unwrap()
    }

    // Take field
    pub fn take_input(&mut self) -> super::input::Input {
        self.input.take().unwrap_or_else(|| super::input::Input::new())
    }
}

impl ::protobuf::Message for RegressionRequest {
    fn is_initialized(&self) -> bool {
        for v in &self.model_spec {
            if !v.is_initialized() {
                return false;
            }
        };
        for v in &self.input {
            if !v.is_initialized() {
                return false;
            }
        };
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_message_into(wire_type, is, &mut self.model_spec)?;
                },
                2 => {
                    ::protobuf::rt::read_singular_message_into(wire_type, is, &mut self.input)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if let Some(ref v) = self.model_spec.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        }
        if let Some(ref v) = self.input.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream) -> ::protobuf::ProtobufResult<()> {
        if let Some(ref v) = self.model_spec.as_ref() {
            os.write_tag(1, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        }
        if let Some(ref v) = self.input.as_ref() {
            os.write_tag(2, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn ::std::any::Any {
        self as &dyn ::std::any::Any
    }
    fn as_any_mut(&mut self) -> &mut dyn ::std::any::Any {
        self as &mut dyn ::std::any::Any
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<dyn ::std::any::Any> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> RegressionRequest {
        RegressionRequest::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_singular_ptr_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<super::model::ModelSpec>>(
                    "model_spec",
                    |m: &RegressionRequest| { &m.model_spec },
                    |m: &mut RegressionRequest| { &mut m.model_spec },
                ));
                fields.push(::protobuf::reflect::accessor::make_singular_ptr_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<super::input::Input>>(
                    "input",
                    |m: &RegressionRequest| { &m.input },
                    |m: &mut RegressionRequest| { &mut m.input },
                ));
                ::protobuf::reflect::MessageDescriptor::new::<RegressionRequest>(
                    "RegressionRequest",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static RegressionRequest {
        static mut instance: ::protobuf::lazy::Lazy<RegressionRequest> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const RegressionRequest,
        };
        unsafe {
            instance.get(RegressionRequest::new)
        }
    }
}

impl ::protobuf::Clear for RegressionRequest {
    fn clear(&mut self) {
        self.model_spec.clear();
        self.input.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for RegressionRequest {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for RegressionRequest {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct RegressionResponse {
    // message fields
    pub model_spec: ::protobuf::SingularPtrField<super::model::ModelSpec>,
    pub result: ::protobuf::SingularPtrField<RegressionResult>,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a RegressionResponse {
    fn default() -> &'a RegressionResponse {
        <RegressionResponse as ::protobuf::Message>::default_instance()
    }
}

impl RegressionResponse {
    pub fn new() -> RegressionResponse {
        ::std::default::Default::default()
    }

    // .tensorflow.ModelSpec model_spec = 2;


    pub fn get_model_spec(&self) -> &super::model::ModelSpec {
        self.model_spec.as_ref().unwrap_or_else(|| super::model::ModelSpec::default_instance())
    }
    pub fn clear_model_spec(&mut self) {
        self.model_spec.clear();
    }

    pub fn has_model_spec(&self) -> bool {
        self.model_spec.is_some()
    }

    // Param is passed by value, moved
    pub fn set_model_spec(&mut self, v: super::model::ModelSpec) {
        self.model_spec = ::protobuf::SingularPtrField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_model_spec(&mut self) -> &mut super::model::ModelSpec {
        if self.model_spec.is_none() {
            self.model_spec.set_default();
        }
        self.model_spec.as_mut().unwrap()
    }

    // Take field
    pub fn take_model_spec(&mut self) -> super::model::ModelSpec {
        self.model_spec.take().unwrap_or_else(|| super::model::ModelSpec::new())
    }

    // .tensorflow.RegressionResult result = 1;


    pub fn get_result(&self) -> &RegressionResult {
        self.result.as_ref().unwrap_or_else(|| RegressionResult::default_instance())
    }
    pub fn clear_result(&mut self) {
        self.result.clear();
    }

    pub fn has_result(&self) -> bool {
        self.result.is_some()
    }

    // Param is passed by value, moved
    pub fn set_result(&mut self, v: RegressionResult) {
        self.result = ::protobuf::SingularPtrField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_result(&mut self) -> &mut RegressionResult {
        if self.result.is_none() {
            self.result.set_default();
        }
        self.result.as_mut().unwrap()
    }

    // Take field
    pub fn take_result(&mut self) -> RegressionResult {
        self.result.take().unwrap_or_else(|| RegressionResult::new())
    }
}

impl ::protobuf::Message for RegressionResponse {
    fn is_initialized(&self) -> bool {
        for v in &self.model_spec {
            if !v.is_initialized() {
                return false;
            }
        };
        for v in &self.result {
            if !v.is_initialized() {
                return false;
            }
        };
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                2 => {
                    ::protobuf::rt::read_singular_message_into(wire_type, is, &mut self.model_spec)?;
                },
                1 => {
                    ::protobuf::rt::read_singular_message_into(wire_type, is, &mut self.result)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if let Some(ref v) = self.model_spec.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        }
        if let Some(ref v) = self.result.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream) -> ::protobuf::ProtobufResult<()> {
        if let Some(ref v) = self.model_spec.as_ref() {
            os.write_tag(2, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        }
        if let Some(ref v) = self.result.as_ref() {
            os.write_tag(1, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn ::std::any::Any {
        self as &dyn ::std::any::Any
    }
    fn as_any_mut(&mut self) -> &mut dyn ::std::any::Any {
        self as &mut dyn ::std::any::Any
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<dyn ::std::any::Any> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> RegressionResponse {
        RegressionResponse::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_singular_ptr_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<super::model::ModelSpec>>(
                    "model_spec",
                    |m: &RegressionResponse| { &m.model_spec },
                    |m: &mut RegressionResponse| { &mut m.model_spec },
                ));
                fields.push(::protobuf::reflect::accessor::make_singular_ptr_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<RegressionResult>>(
                    "result",
                    |m: &RegressionResponse| { &m.result },
                    |m: &mut RegressionResponse| { &mut m.result },
                ));
                ::protobuf::reflect::MessageDescriptor::new::<RegressionResponse>(
                    "RegressionResponse",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static RegressionResponse {
        static mut instance: ::protobuf::lazy::Lazy<RegressionResponse> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const RegressionResponse,
        };
        unsafe {
            instance.get(RegressionResponse::new)
        }
    }
}

impl ::protobuf::Clear for RegressionResponse {
    fn clear(&mut self) {
        self.model_spec.clear();
        self.result.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for RegressionResponse {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for RegressionResponse {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Message(self)
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x10regression.proto\x12\ntensorflow\x1a\x0binput.proto\x1a\x0bmodel.p\
    roto\"\"\n\nRegression\x12\x14\n\x05value\x18\x01\x20\x01(\x02R\x05value\
    \"L\n\x10RegressionResult\x128\n\x0bregressions\x18\x01\x20\x03(\x0b2\
    \x16.tensorflow.RegressionR\x0bregressions\"r\n\x11RegressionRequest\x12\
    4\n\nmodel_spec\x18\x01\x20\x01(\x0b2\x15.tensorflow.ModelSpecR\tmodelSp\
    ec\x12'\n\x05input\x18\x02\x20\x01(\x0b2\x11.tensorflow.InputR\x05input\
    \"\x80\x01\n\x12RegressionResponse\x124\n\nmodel_spec\x18\x02\x20\x01(\
    \x0b2\x15.tensorflow.ModelSpecR\tmodelSpec\x124\n\x06result\x18\x01\x20\
    \x01(\x0b2\x1c.tensorflow.RegressionResultR\x06resultB\x03\xf8\x01\x01J\
    \xdb\x07\n\x06\x12\x04\0\0$\x01\n\x08\n\x01\x0c\x12\x03\0\0\x12\n\x08\n\
    \x01\x08\x12\x03\x02\0\x1f\n\x0b\n\x04\x08\xe7\x07\0\x12\x03\x02\0\x1f\n\
    \x0c\n\x05\x08\xe7\x07\0\x02\x12\x03\x02\x07\x17\n\r\n\x06\x08\xe7\x07\0\
    \x02\0\x12\x03\x02\x07\x17\n\x0e\n\x07\x08\xe7\x07\0\x02\0\x01\x12\x03\
    \x02\x07\x17\n\x0c\n\x05\x08\xe7\x07\0\x03\x12\x03\x02\x1a\x1e\n\t\n\x02\
    \x03\0\x12\x03\x04\x07\x14\n\t\n\x02\x03\x01\x12\x03\x05\x07\x14\n\x08\n\
    \x01\x02\x12\x03\x07\x08\x12\nG\n\x02\x04\0\x12\x04\n\0\x0c\x01\x1a;\x20\
    Regression\x20result\x20for\x20a\x20single\x20item\x20(tensorflow.Exampl\
    e).\n\n\n\n\x03\x04\0\x01\x12\x03\n\x08\x12\n\x0b\n\x04\x04\0\x02\0\x12\
    \x03\x0b\x02\x12\n\r\n\x05\x04\0\x02\0\x04\x12\x04\x0b\x02\n\x14\n\x0c\n\
    \x05\x04\0\x02\0\x05\x12\x03\x0b\x02\x07\n\x0c\n\x05\x04\0\x02\0\x01\x12\
    \x03\x0b\x08\r\n\x0c\n\x05\x04\0\x02\0\x03\x12\x03\x0b\x10\x11\nj\n\x02\
    \x04\x01\x12\x04\x10\0\x12\x01\x1a^\x20Contains\x20one\x20result\x20per\
    \x20input\x20example,\x20in\x20the\x20same\x20order\x20as\x20the\x20inpu\
    t\x20in\n\x20RegressionRequest.\n\n\n\n\x03\x04\x01\x01\x12\x03\x10\x08\
    \x18\n\x0b\n\x04\x04\x01\x02\0\x12\x03\x11\x02&\n\x0c\n\x05\x04\x01\x02\
    \0\x04\x12\x03\x11\x02\n\n\x0c\n\x05\x04\x01\x02\0\x06\x12\x03\x11\x0b\
    \x15\n\x0c\n\x05\x04\x01\x02\0\x01\x12\x03\x11\x16!\n\x0c\n\x05\x04\x01\
    \x02\0\x03\x12\x03\x11$%\n\x1d\n\x02\x04\x02\x12\x04\x16\0\x1d\x012\x11\
    \x20RPC\x20interfaces.\n\n\n\n\x03\x04\x02\x01\x12\x03\x16\x08\x19\nj\n\
    \x04\x04\x02\x02\0\x12\x03\x19\x02\x1b\x1a]\x20Model\x20Specification.\
    \x20If\x20version\x20is\x20not\x20specified,\x20will\x20use\x20the\x20la\
    test\n\x20(numerical)\x20version.\n\n\r\n\x05\x04\x02\x02\0\x04\x12\x04\
    \x19\x02\x16\x1b\n\x0c\n\x05\x04\x02\x02\0\x06\x12\x03\x19\x02\x0b\n\x0c\
    \n\x05\x04\x02\x02\0\x01\x12\x03\x19\x0c\x16\n\x0c\n\x05\x04\x02\x02\0\
    \x03\x12\x03\x19\x19\x1a\n\x1a\n\x04\x04\x02\x02\x01\x12\x03\x1c\x02\x1d\
    \x1a\r\x20Input\x20data.\n\n\r\n\x05\x04\x02\x02\x01\x04\x12\x04\x1c\x02\
    \x19\x1b\n\x0c\n\x05\x04\x02\x02\x01\x06\x12\x03\x1c\x02\x12\n\x0c\n\x05\
    \x04\x02\x02\x01\x01\x12\x03\x1c\x13\x18\n\x0c\n\x05\x04\x02\x02\x01\x03\
    \x12\x03\x1c\x1b\x1c\n\n\n\x02\x04\x03\x12\x04\x1f\0$\x01\n\n\n\x03\x04\
    \x03\x01\x12\x03\x1f\x08\x1a\nA\n\x04\x04\x03\x02\0\x12\x03!\x02\x1b\x1a\
    4\x20Effective\x20Model\x20Specification\x20used\x20for\x20regression.\n\
    \n\r\n\x05\x04\x03\x02\0\x04\x12\x04!\x02\x1f\x1c\n\x0c\n\x05\x04\x03\
    \x02\0\x06\x12\x03!\x02\x0b\n\x0c\n\x05\x04\x03\x02\0\x01\x12\x03!\x0c\
    \x16\n\x0c\n\x05\x04\x03\x02\0\x03\x12\x03!\x19\x1a\n\x0b\n\x04\x04\x03\
    \x02\x01\x12\x03#\x02\x1e\n\r\n\x05\x04\x03\x02\x01\x04\x12\x04#\x02!\
    \x1b\n\x0c\n\x05\x04\x03\x02\x01\x06\x12\x03#\x02\x12\n\x0c\n\x05\x04\
    \x03\x02\x01\x01\x12\x03#\x13\x19\n\x0c\n\x05\x04\x03\x02\x01\x03\x12\
    \x03#\x1c\x1db\x06proto3\
";

static mut file_descriptor_proto_lazy: ::protobuf::lazy::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::lazy::Lazy {
    lock: ::protobuf::lazy::ONCE_INIT,
    ptr: 0 as *const ::protobuf::descriptor::FileDescriptorProto,
};

fn parse_descriptor_proto() -> ::protobuf::descriptor::FileDescriptorProto {
    ::protobuf::parse_from_bytes(file_descriptor_proto_data).unwrap()
}

pub fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    unsafe {
        file_descriptor_proto_lazy.get(|| {
            parse_descriptor_proto()
        })
    }
}
